---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: mocon
    password: mocon
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zenstain/springcloudconfig
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/zenstain/springcloud-performance-config
              search-paths:
                - 'station*'